### ISSUE TITLE
faoutlier - forward.search, why 10 values?

### ISSUE THREAD

**Issue by yashbhambhani** [philchalmers/faoutlier#2]
So I'm trying to use the faoutlier package and forward.search function to run an outlier analysis in an EFA dataset, and in default mode [forward.search(data, number of factors)], it returns only 10 values - and it returns only 10 values if i specify cri="mah" (mahalanobis) as well. Why is that so? And when its running in default, what is it actually running? Because running default and mahalanobis is giving me different answers

**Comment by philchalmers** [comment]
Are you certain it's returning the top 10, or just printing those? The default prints the top extreme cases, but you can used other methods to display the rest of the case values.

**Comment by yashbhambhani** [comment]
Hi Dr. Chalmers - Thank you for your comment.
Its simply printing 10 values - attached is a screenshot of the output. 
I'm also having trouble understanding what it is running in the default option - mahalanobis distance along with something else?
<img width="594" alt="screen shot 2016-04-01 at 9 13 37 pm" src="https://cloud.githubusercontent.com/assets/18223696/14223943/e97a18bc-f850-11e5-993e-f9f2c9bf878d.png">

**Comment by philchalmers** [comment]
The GOF statistic as well, but others can also be included. See the ?GOF help file for details. It might be good to work through those functions first before experimenting with a forward.search function (which is really only useful if you think there are 'clusters') of outliers. Cheers.

**Comment by yashbhambhani** [comment]
Ok - i will. Thank you for the help!

**Comment by seonghobae** [comment]
Hi, Phil.
Can I select outliers these tuples in this an issue? (160, 162, 77, 169, 203, 258, 3, 316, 341, 35)
I can't understand even I read a manual.

Seongho
